# -*- coding: utf-8 -*-
"""ML Task 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kKOszOP2iGQsQk_wpmN22rLo5Y_Dilfi
"""

# ===============================
# STEP 1: IMPORT REQUIRED LIBRARIES
# We import PyTorch, datasets, and tools for training a neural network
# ==============================================================
import torch
import torch.nn as nn
import torch.optim as optim

from torchvision import datasets, transforms
from torch.utils.data import DataLoader, random_split

import matplotlib.pyplot as plt
import pandas as pd

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

# ===============================
# STEP 3: LOAD FASHION-MNIST DATASET
# This dataset contains 28x28 grayscale images of clothing items
# ===============================

transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5,), (0.5,))
])

train_dataset = datasets.FashionMNIST(
    root="./data",
    train=True,
    download=True,
    transform=transform
)

test_dataset = datasets.FashionMNIST(
    root="./data",
    train=False,
    download=True,
    transform=transform
)

# ===============================
# STEP 4: SPLIT DATA INTO TRAIN AND VALIDATION SET
# 80% training data, 20% validation data
# ===============================
train_size = int(0.8 * len(train_dataset))
val_size = len(train_dataset) - train_size

train_dataset, val_dataset = random_split(train_dataset, [train_size, val_size])

# ===============================
# STEP 5: CREATE DATALOADERS
# DataLoaders help load data in batches for training efficiency
# ===============================
batch_size = 64

train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

# ===============================
# STEP 6: BUILD NEURAL NETWORK MODEL
# This is a simple feed-forward neural network (MLP)
# It converts images into predictions (0–9 classes)
# ===============================

class FashionModel(nn.Module):
    def __init__(self):
        super().__init__()

        self.net = nn.Sequential(
            nn.Flatten(),
            nn.Linear(28*28, 256),
            nn.ReLU(),
            nn.Linear(256, 128),
            nn.ReLU(),
            nn.Linear(128, 10)
        )

    def forward(self, x):
        return self.net(x)

# ===============================
# STEP 7: INITIALIZE MODEL, LOSS FUNCTION, OPTIMIZER
# Loss function measures error
# Optimizer updates model weights
# ===============================
model = FashionModel().to(device)

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

# ===============================
# STEP 8: TRAINING FUNCTION
# This function trains the model on training data
# It updates weights using backpropagation
# ===============================
def train_one_epoch(model, loader):
    model.train()

    total_loss = 0
    correct = 0
    total = 0

    for x, y in loader:
        x, y = x.to(device), y.to(device)

        optimizer.zero_grad()

        outputs = model(x)
        loss = criterion(outputs, y)

        loss.backward()
        optimizer.step()

        total_loss += loss.item()

        preds = torch.argmax(outputs, dim=1)
        correct += (preds == y).sum().item()
        total += y.size(0)

    return total_loss / len(loader), correct / total

# ===============================
# STEP 9: VALIDATION FUNCTION
# This checks model performance on unseen data
# No weight updates happen here
# ===============================
def evaluate(model, loader):
    model.eval()

    total_loss = 0
    correct = 0
    total = 0

    with torch.no_grad():
        for x, y in loader:
            x, y = x.to(device), y.to(device)

            outputs = model(x)
            loss = criterion(outputs, y)

            total_loss += loss.item()

            preds = torch.argmax(outputs, dim=1)
            correct += (preds == y).sum().item()
            total += y.size(0)

    return total_loss / len(loader), correct / total

# ===============================
# STEP 10: TRAINING LOOP
# Repeats training + validation for multiple epochs
# Shows improvement over time
# ===============================
epochs = 10

train_losses, val_losses = [], []
train_accs, val_accs = [], []

for epoch in range(epochs):

    train_loss, train_acc = train_one_epoch(model, train_loader)
    val_loss, val_acc = evaluate(model, val_loader)

    train_losses.append(train_loss)
    val_losses.append(val_loss)
    train_accs.append(train_acc)
    val_accs.append(val_acc)

    print(f"Epoch {epoch+1}/{epochs}")
    print(f"Train Loss: {train_loss:.4f} | Train Acc: {train_acc:.4f}")
    print(f"Val Loss: {val_loss:.4f} | Val Acc: {val_acc:.4f}")
    print("-"*40)

# ===============================
# STEP 11: VISUALIZE RESULTS
# Shows loss curve to understand model learning
# ===============================
plt.figure()
plt.plot(train_losses, label="Train Loss")
plt.plot(val_losses, label="Val Loss")
plt.legend()
plt.title("Loss Curve")
plt.show()

plt.figure()
plt.plot(train_accs, label="Train Accuracy")
plt.plot(val_accs, label="Val Accuracy")
plt.legend()
plt.title("Accuracy Curve")
plt.show()

torch.save(model.state_dict(), "fashion_mnist_model.pth")
print("Model saved successfully!")

# ===============================
# STEP 12: SAVE TRAINED MODEL
# Saves learned weights so we can reuse model later
# ===============================
model = FashionModel().to(device)
model.load_state_dict(torch.load("fashion_mnist_model.pth"))
model.eval()

# ===============================
# STEP 13: MAKE PREDICTIONS ON TEST DATA
# Model predicts labels for unseen test images
# ===============================
model.eval()
predictions = []

with torch.no_grad():
    for x, _ in test_loader:
        x = x.to(device)

        outputs = model(x)
        preds = torch.argmax(outputs, dim=1)

        predictions.extend(preds.cpu().numpy())

# ===============================
# STEP 14: CREATE SUBMISSION FILE
# Stores predictions in required format (id, label)
# ===============================
submission = pd.DataFrame({
    "id": list(range(len(predictions))),
    "label": predictions
})

submission.to_csv("submission.csv", index=False)

print("submission.csv created successfully!")

from google.colab import files
files.download("submission.csv")